### ISSUE TITLE
iPhone X issues

### ISSUE THREAD

**Issue by ETGgames** [hackiftekhar/IQKeyboardManager#1036]
When a text field that is constrained to the bottom of the safe area, or constrained to the bottom of the background image, and on iPhone X, then sometimes the keyboard covers the text field area. I think this is because of the way the background that is constrained to the top goes above the nav bar on iPhone X. 
<img width="363" alt="screen shot 2017-10-02 at 21 58 02" src="https://user-images.githubusercontent.com/13756744/31099115-d2f60912-a7bc-11e7-9a58-670713f4bd4c.png">
<img width="413" alt="screen shot 2017-10-02 at 21 58 11" src="https://user-images.githubusercontent.com/13756744/31099120-d49704a6-a7bc-11e7-8fe5-8c53e7d07798.png">

**Comment by hackiftekhar** [comment]
I tried to handle some issues in v5.0.3 caused by safe Area. Let's see how it works.

**Comment by ETGgames** [comment]
ah, works now. cheers.

**Comment by brightsider** [comment]
In UIScrollView bottom inset has extra space
![tableview](https://user-images.githubusercontent.com/4996231/31213259-5031287e-a9ae-11e7-9c19-ee951db2d19a.png)

**Comment by hackiftekhar** [comment]
@brightsider your issue isn't related this one, can you open a new issue?

**Comment by tolotrasmile** [comment]
<img width="1280" alt="screen shot 2017-10-26 at 17 46 47" src="https://user-images.githubusercontent.com/8298581/32059763-c7308820-ba75-11e7-8322-0f51a0880365.png">
I Have the same issue on iPhone X Simulator using IQKeyboardManagerSwift (5.0.4).
There is the screen shout.

**Comment by invinciible** [comment]
![simulator screen shot - iphone x - 2017-12-08 at 18 24 46](https://user-images.githubusercontent.com/25017046/33766797-1c8152f0-dc45-11e7-9eb4-7a82443712f8.png)
Ah! I'm still facing the same issue with v5.0.6, I hope you'll fix it soon.

**Comment by ETGgames** [comment]
Yeah it has stopped working again. Only works half the time.

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.

**Comment by machive** [comment]
Well, I have this problem under 5.0.7, and when I specify 6.0.0 in the Podfile, I lose my ability to select input fields in the simulator! If I go back to 5.0.7, it works again, but I still have the problem with the keyboard covering up half of the input field. 

Any ideas what I should do?

**Comment by machive** [comment]
Hello, 

  Thanks for the response. v6.0.1 does not have the same problem with the simulator but the keyboard is still covering up half of my input field, at least the first time I click on the input field. I thought your changes were supposed to take care of this problem. Is there anything else I need to do?

**Comment by machive** [comment]
Hello, 
  Any thoughts? 

  Best,

  Larry

**Comment by hackiftekhar** [comment]
Can you please share demo project?

**Comment by machive** [comment]
To be honest, I'm probably not going to have the time to create a demo project.

**Comment by hackiftekhar** [comment]
Something similar issue with me. If I don't get the demo project to reproduce issue then how can I fix the issue?

**Comment by encikpulasan** [comment]
Hi, i shared my solution on thread #1273, kindly look if it helps. Too many thread with same problem.

**Comment by encikpulasan** [comment]
@machive u can set `[setKeyboardDistanceFromTextField]` to only specific controller that need fixing, put it in `viewWillAppear()` and reset the value back on `viewDidDisappear()` so it didnt effect other controllers.
