### ISSUE TITLE
Status bar disappears in iOS 11

### ISSUE THREAD

**Issue by jaymathew** [hackiftekhar/IQKeyboardManager#1122]
Hello, 

The following issue only happens on iOS 11 and on both simulator and real devices. 
 
When the keyboard comes up everything is fine, but when I tap done the keyboard lowers and I have no status bar left and all components on that view are moved up.  The next time the keyboard rises and lowers the status bar is back.  The missing status bar happens ever other raise and lower of the keyboard.  Below are some screenshots that help relay the issue, the black marks are my vertical constraints that connect the bottom and top of the view.  The TextView at the bottom doesn't have a height constraint so on smaller devices it shrinks 

![demo 2](https://user-images.githubusercontent.com/8115938/32633076-b44b5ad6-c56b-11e7-91ca-52a71962de9c.png)
![demo1](https://user-images.githubusercontent.com/8115938/32633080-b794b5e8-c56b-11e7-8fed-76d96f70cbdd.png)

**Comment by hackiftekhar** [comment]
iOS11 introduce lots of new features which affects library very badly.

**Comment by jaymathew** [comment]
Is a fix on the way?

**Comment by GamexStudio** [comment]
I am facing the same issue. Is there any workaround for this?

**Comment by hackiftekhar** [comment]
Currently no workaround. Can someone upload sample code to reproduce this issue?

**Comment by rdaneshvar95** [comment]
No solution yet? @hackiftekhar

**Comment by ugomarinelli** [comment]
Hi guys, my workaround was : 

In IQKeyboardManager.swift, inside the **keyboardDidHide** method, add the following : 

   
	let statusBar: UIView = UIApplication.shared.value(forKey: "statusBar") as! UIView

    if statusBar.responds(to:#selector(setter: UIView.backgroundColor)) {
        statusBar.backgroundColor = UIColor.white
    }

in the end, your keyboardDidHide look like this : 
		
	             
	@objc internal func keyboardDidHide(_ notification:Notification) {

        let startTime = CACurrentMediaTime()
        showLog("****** \(#function) started ******")
        
        _topViewBeginRect = CGRect.zero
        
        let statusBar: UIView = UIApplication.shared.value(forKey: "statusBar") as! UIView

        if statusBar.responds(to:#selector(setter: UIView.backgroundColor)) {
            statusBar.backgroundColor = UIColor.white
        }
        
	#if swift(>=3.2)
        if #available(iOS 11, *) {
            _initialAdditionalSafeAreaInsets = .zero;
        }
	#endif
        
        _kbSize = CGSize.zero

        let elapsedTime = CACurrentMediaTime() - startTime
        showLog("****** \(#function) ended: \(elapsedTime) seconds ******")
    }

I know it is maybe not the best since I harcoded the background to be white but that made the trick for me

**Comment by seonift** [comment]
i have same issue...

**Comment by vaibhavmane** [comment]
IQKeyboardManager.sharedManager().enable = false you can do like in your particular view controller

**Comment by rdaneshvar95** [comment]
Here is the solution:
#1190 
@seonift

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.

**Comment by nCr78** [comment]
This still happens for some reason even when having the deprecated "canAdjustAdditionalSafeAreaInsets" boolean set to true. (Using v6.0.0 from cocoapods)

Disabling the manager stops it from happening so it can't possibly be my implementation..

**Comment by hackiftekhar** [comment]
@nCr78 can you please share a demo project using v6.0.0?

**Comment by nCr78** [comment]
@hackiftekhar Yes give me some time to isolate my implementation and I'll upload a gist of a view controller

**Comment by hackiftekhar** [comment]
It would be better if you provide the demo project instead of code of a single view controller. It's better for me otherwise I'll have to do extra work to integrate your code to another demo project and all that.

**Comment by nCr78** [comment]
Alright, will do it as a project! No problem :)

**Comment by nCr78** [comment]
Upon trying to isolate and reproduce the issue onto a new project, I found out that it's caused by a combination of your project and another open source project. This complicates things because I don't know exactly which parts of each project are conflicting except from their custom tab bar controller.

On top of that, I could only reproduce it on a physical iPhone X (iOS 11+). I've tried the simulator and the status bar stays as it is. I ran it on a physical iPhone 7 (iOS 11+) and the issue isn't there either.

Here's the project in case you want to check it out. I might have to change my implementation as I don't see how this is fixable - my guess is safe areas and UIView extension conflicts.

[keyboardtest.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1914181/keyboardtest.zip)

![img_0663](https://user-images.githubusercontent.com/1726629/38795108-e444dcb0-415f-11e8-9087-b0a7169ea788.png)

**Comment by hackiftekhar** [comment]
I started reviewing the demo project. However I don't have physical iPhoneX or iPhone8+ size device so I'm unable to reproduce this issue with this demo project and as you said it isn't reproducible with simulators. :(

**Comment by CornerStone12** [comment]
I have the same problem. Tried upgrading to 6.0.4 but it still happens. Using iPhone6. Solutions for setting status bar color to white is not a solution, it just sets the status bar color to white ;-) Really need a fix for this.
Also, on one of my ViewControllers the arrows are the wrong way around. Any advice on how to fix that?

**Comment by hackiftekhar** [comment]
with the arrow fix, please make sure your textFields are in correct order in view hierarchy since it mostly happens with wrong view hierarchy.

**Comment by caijingsong** [comment]
i try to fix the bug.
have try in IOKeyboardManager.m:
- (void)keyboardDidHide:(NSNotification*)aNotification
{
    CFTimeInterval startTime = CACurrentMediaTime();
    [self showLog:[NSString stringWithFormat:@"****** %@ started ******",NSStringFromSelector(_cmd)]];

    _topViewBeginRect = CGRectZero;
    
    [[UIApplication sharedApplication].keyWindow setNeedsLayout];

    CFTimeInterval elapsedTime = CACurrentMediaTime() - startTime;
    [self showLog:[NSString stringWithFormat:@"****** %@ ended: %g seconds ******",NSStringFromSelector(_cmd),elapsedTime]];
}

**Comment by codenia** [comment]
I can also see this problem on the iPhone 6, 7 Plus and iPhone Xs Max. It does not happen the first time after closing the keyboard. 
If I touch a text field, the keyboard pops up, then I close the keyboard and the status bar is still there. But if I touch the same text field for the second time, the keyboard pops up, then I close the keyboard and the status bar has disappeared. If I now touch the same text box again, the keyboard opens, I close the keyboard and the status bar is back.

It works in this pattern:

1. status bar is OK
2. status bar is NOK
3. status bar is OK
4. status bar is OK
5. status bar is NOK
6. status bar is OK
7. status bar is OK
8. status bar is NOK
.....

So the behavior has a system. My keyboard settings are set like this:

![screen](https://user-images.githubusercontent.com/25936712/46289807-64acb900-c58a-11e8-9618-b72f9ec19336.png)

**Comment by codenia** [comment]
I found the cause of the problem in my code. In the function viewDidLayoutSubviews I read and use the view.safeAreaInsets.top value. Sometimes if the keyboard show up the viewDidLayoutSubviews function is called. The value of view.safeAreaInsets.top is sometimes 0 instead of 20 or 44.

That's how I solved the problem:

```
- (void)viewDidLayoutSubviews
{
    [super viewDidLayoutSubviews];
    
    UIEdgeInsets safeAreaInsets;
    
    safeAreaInsets.left = 0;
    safeAreaInsets.right = 0;
    safeAreaInsets.top = [UIApplication sharedApplication].statusBarFrame.size.height;
    safeAreaInsets.bottom = 0;
    
    if (@available(iOS 11.0, *)) {
        safeAreaInsets.left = view.safeAreaInsets.left;
        safeAreaInsets.right = view.safeAreaInsets.right;
        if(self.view.safeAreaInsets.top != 0)
        {
            safeAreaInsets.top = self.view.safeAreaInsets.top;
        }
        
        if(self.view.safeAreaInsets.bottom != 0)
        {
            safeAreaInsets.bottom = self.view.safeAreaInsets.bottom;
        }
    }

   // some layout code
   ...
}
```

**Comment by nobird** [comment]
try "IQKeyboardManager.shared().layoutIfNeededOnUpdate = true" 
It works for me..

**Comment by Rajkiran93** [comment]
> try "IQKeyboardManager.shared().layoutIfNeededOnUpdate = true"
> It works for me..

Thanks works for me too...
