### ISSUE TITLE
shouldResignOnTouchOutsideMode is not working

### ISSUE THREAD

**Issue by cuong1112035** [hackiftekhar/IQKeyboardManager#1369]
### Description

Hi all

Currenlly, shouldResignOnTouchOutsideMode = .disable is not working for me. It is invoked on a UITextField.
Below is my global keyboard settings: 
IQKeyboardManager.shared.enable = true        
IQKeyboardManager.shared.enableAutoToolbar = false
IQKeyboardManager.shared.shouldResignOnTouchOutside = true        IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(BaseOnboardingViewController.self)        IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(ZDCChatViewController.self)        IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(SupportViewController.self)
IQKeyboardManager.shared.disabledToolbarClasses = [ZDCChatViewController.self, BaseOnboardingViewController.self, LoginViewController.self, SupportViewController.self]
IQKeyboardManager.shared.enabledToolbarClasses.append(PlaceTradeViewController.self)

Pleas help

### Versions

**Xcode:** 9.4

**Mac OS:** 10.13.4

**Simulator/Device:** 11.4

**Simulator/Device Name:** iPhone 7 plus

**Library Version:** 6.0.4

**Comment by hackiftekhar** [comment]
You was correct. There was an issue with it's getter which was preventing to return correct value. It's fixed now in master.

**Comment by cuong1112035** [comment]
@hackiftekhar I just checked it, still not working. I am using latest version (6.0.4)

**Comment by hackiftekhar** [comment]
I said, it's fixed in master branch, the changes not released with cocoapods yet.

**Comment by cuong1112035** [comment]
ah thanks, I got it
