### ISSUE TITLE
Reference that makes memory leak

### ISSUE THREAD

**Issue by vpavloviclevi9** [hackiftekhar/IQKeyboardManager#2038]
**Describe the bug**
Since version 7.0.0. (also with the latest version 7.0.2) IQKeyboardManager instance holds reference to the last focused text field even keyboard is dismissed, which makes memory leak and side effects on host application (as in my case). With version 6.5.16 no such issues.

**To Reproduce**
Initialize IQKeyboardManager in AppDelegate

```
IQKeyboardManager.shared.enable = true
IQKeyboardManager.shared.enableAutoToolbar = false
IQKeyboardManager.shared.resignOnTouchOutside = true
```

Ensure the text field is the focus and dismiss the keyboard. Transition to another ViewController, ensuring it's not retained in the navigation stack. Although the specific ViewController is no longer part of the view hierarchy, it remains in the memory graph, which causes a memory leak and in my case app side effects.

**Expected behavior**
If keyboard is dismissed it shoudn't hold any reference to input fields.

**Screenshots**
Here is the memory graph:
![image](https://github.com/hackiftekhar/IQKeyboardManager/assets/58295108/411768c4-1fc0-4f00-9371-dad10a9bca14)

**Demo Project**
n/a

### Versions
**Xcode:** 15.3
**Mac OS:** 14.4.1
**Simulator/Device:** both on simulator and device
**Simulator/Device Name:** iPhone 15
**Library Version:** 7.0.0./ 7.0.1./ 7.0.2.

**Additional context**
n/a

**Comment by hackiftekhar** [comment]
Thanks for reporting this issue. I'll investigate it and see why this is happening.

**Comment by Pnaveen1513** [comment]
IQKeyboardManager.shared.enable = true
IQKeyboardManager.shared.enableAutoToolbar = false
IQKeyboardManager.shared.resignOnTouchOutside = true

**Comment by yueno12** [comment]
+1

**Comment by vpavloviclevi9** [comment]
@hackiftekhar any news on this?

**Comment by NovichenkoAnton** [comment]
+1

**Comment by artemborisenko** [comment]
Same problem

**Comment by mmatiush** [comment]
+1
I have the same problem. It holds any view controller with a UITextField in memory even after the view controller was popped.

**Comment by mmatiush** [comment]
@hackiftekhar maybe you have any updates?

**Comment by hackiftekhar** [comment]
I have tried to fix the issue however haven't tested my changes in different scenarios. So I would like to ask you guys to test the master branch version to see if you are able to still reproduce memory leaks in your situations and also test if everything works well for you. Till then I would like to keep this issue open.

**Comment by hackiftekhar** [comment]
Thanks @Sukarma33 for notifying that your problem is solved.

**Comment by burhonov007** [comment]
I had the same problem, just hide keyboard before dismissing ViewController, it helped for me 😊

**Comment by vpavloviclevi9** [comment]
The issue is still there, even with version 7.1.1

Someone else also has the same issue, so I'll leave this ticket closed.

https://github.com/hackiftekhar/IQKeyboardManager/issues/2055

**Comment by hackiftekhar** [comment]
I tried to fix it with some weak referencing and handled some pop gesture cases.
Can you guys check master branch and see if issue is still there.
