### ISSUE TITLE
Cannot build IQKeyboardManager with Carthage ! - Xcode 7.3

### ISSUE THREAD

**Issue by awesomeswift** [hackiftekhar/IQKeyboardManager#481]
*** Fetching IQKeyboardManager
*** Checking out IQKeyboardManager at "v4.0.1"
*** xcodebuild output can be found in /var/folders/9b/bmy1_4g94293dydhr3s_v4gm0000gp/T/carthage-xcodebuild.wHV6Sa.log
*** Building scheme "IQKeyboardManagerSwift" in IQKeyboardManagerSwift.xcodeproj
2016-04-07 17:47:53.305 xcodebuild[25163:2295967] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VWInstantRun.xcplugin' not present in DVTPlugInCompatibilityUUIDs
** BUILD FAILED **

The following build commands failed:
        CompileSwift normal arm64 /Users/awesomeswift/Workspace/Magneto/App/EMag/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManagerSwift/IQKeyboardManager.swift
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by awesomeswift** [comment]
but, it worked with this command : github "hackiftekhar/IQKeyboardManager" == 4.0.0
anw, please fix this issue

**Comment by clooth** [comment]
This is fixed in the master branch as far as I can tell.

**Comment by hackiftekhar** [comment]
Yup, it's fixed in master branch.

**Comment by awesomeswift** [comment]
@hackiftekhar,
It's still failing 

** BUILD FAILED **


The following build commands failed:
        CompileSwift normal arm64 /Users/awesomeswift/Workspace/AwesomeS/iOS/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManagerSwift/IQKeyboardManager.swift
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/awesomeswift/Workspace/AwesomeS/iOS/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManagerSwift/IQKeyboardManager.swift:804:68: error: use of unresolved identifier 'IQPreviousNextView'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
        CompileSwift normal arm64 /Users/awesomeswift/Workspace/AwesomeS/iOS/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManagerSwift/IQKeyboardManager.swift
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by techmehra** [comment]
Yes, It's still failing . i am also getting the same error after upgrading to xcode 7.3

**Comment by hackiftekhar** [comment]
4.0.2 has now been pushed with the fix via cocoapods.
