### ISSUE TITLE
carthage failed @v4.0.4

### ISSUE THREAD

**Issue by CodeEagle** [hackiftekhar/IQKeyboardManager#575]
when carthage compile ,error `Failed to read file or folder at`

**Comment by hackiftekhar** [comment]
I need to check.

**Comment by CodeEagle** [comment]
![image](https://cloud.githubusercontent.com/assets/2311352/17010381/fa410a3e-4f35-11e6-8b20-26346af61eec.png)

**Comment by andrey-krukovskiy** [comment]
Seems, in ```IQKeyboardManager/Demo/Objective_C_Demo/Resources/Info.plist``` ```CFBundlePackageType ``` was ```APPL``` and not ```FMWK```. That was a reason why carthage does not read and not copy framework, I think.
It was fixed in some of the next commits.

**Comment by smebberson** [comment]
This is still occurring. Are you able to make a new release, or do I just make Carthage build from master (somehow)?

**Comment by hackiftekhar** [comment]
I'll release a new build soon.

**Comment by smebberson** [comment]
@hackiftekhar, thanks.
