### ISSUE TITLE
Scroll not working as expected in UITableView inside a UIStackView ?

### ISSUE THREAD

**Issue by varun-naharia** [hackiftekhar/IQKeyboardManager#805]
I am facing problem only on one screen where scroll is happening but my textview hidden behind another view on the same UIViewController.

![x1h72ipnge](https://cloud.githubusercontent.com/assets/10987732/24397510/10afb45c-13c4-11e7-8583-ae9ece1a60a6.gif)

What I am doing wrong here how to fix this.

![screen shot 2017-03-28 at 2 39 27 pm](https://cloud.githubusercontent.com/assets/10987732/24397646/8da3b99a-13c4-11e7-921a-dfe765675da7.png)
View Hierarchy

**Comment by hackiftekhar** [comment]
@varun-naharia Looks like you are having a complex hierarchy StackView->StackView->tableView->Cell. There might be something which confusing the library to do proper calculations or somthing like that. Can you provide me a demo project so that I can debug it?

**Comment by varun-naharia** [comment]
here is the requested demo project
[iQ-BugDemo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/892408/iQ-BugDemo.zip)

**Comment by hackiftekhar** [comment]
Thanks @varun-naharia for demo.

**Comment by varun-naharia** [comment]
Any progress ? if explain how to solve this then may be I'll solve this and send you pull request

**Comment by hackiftekhar** [comment]
Hey @varun-naharia I checked the demo just now, I think library is doing fine, the reason is that the library is maintaining distance between keyboard and textField and this is why your textField scroll and hide itself. You can set keyboardDistanceFromTextField either on textField object or globally in IQKeyboardManager class, so app will try to maintain less distance which might work for you. Default distance is 10pt. Let me know if this doesn't solve your issue.

**Comment by varun-naharia** [comment]
no it didn't solve the problem, I set 'cell.txtDestination.keyboardDistanceFromTextField = 1' but results are same

**Comment by varun-naharia** [comment]
is there any other way by which I can solve the issue ?

**Comment by hackiftekhar** [comment]
@varun-naharia I think your solution should fix the problem, but if it does not then can you try setting global `keyboardDistanceFromTextField` of IQKeyboardManager?

**Comment by varun-naharia** [comment]
I tried both but it didn't fix the problem you can check solution in demo project.

**Comment by varun-naharia** [comment]
@hackiftekhar I added these line to IQKeyboardManager on line number 1071 and it fixed it. **Please check if it is correct way to fix it ?**

```
if((textFieldView.superviewOfClassType(UITableView.self)) != nil)
        {
            superView = nil
        }
```
